package server

import (
	"github.com/timpalpant/yahtzee"
)

// GameState represents the current state of the game at the beginning
// of the turn.
type GameState struct {
	Filled               []bool
	YahtzeeBonusEligible bool
	UpperHalfScore       int
	TotalScore           int
}

func FromYahtzeeGameState(game yahtzee.GameState) GameState {
	filled := make([]bool, yahtzee.NumTurns)
	for i := range filled {
		filled[i] = true
	}
	for _, box := range game.AvailableBoxes() {
		filled[int(box)] = false
	}

	return GameState{
		Filled:               filled,
		YahtzeeBonusEligible: game.BonusEligible(),
		UpperHalfScore:       game.UpperHalfScore(),
		TotalScore:           game.TotalScore(),
	}
}

func (gs GameState) ToYahtzeeGameState() yahtzee.GameState {
	game := yahtzee.NewGame()
	for box, filled := range gs.Filled {
		if filled {
			game = game.SetBoxFilled(yahtzee.Box(box))
		}
	}

	if gs.YahtzeeBonusEligible {
		game = game.SetBonusEligible()
	}

	game = game.AddUpperHalfScore(gs.UpperHalfScore)
	game = game.AddScore(gs.TotalScore)
	return game
}

// TurnState represents the current progress through a turn.
// In all cases, Dice are the current 5 dice after the previous roll.
type TurnState struct {
	Step yahtzee.TurnStep
	Dice []int
}

// GetScoreRequest gets the score generated by playing the given
// dice in the given box.
//
// NOTE: The returned score does not include any bonuses that
// could be generated as a side-effect.
type GetScoreRequest struct {
	Dice []int
	Box  int
}

type GetScoreResponse struct {
	Score int
}

// OptimalMoveRequest gets the best move to make given the current
// turn state.
type OptimalMoveRequest struct {
	GameState GameState
	TurnState TurnState

	// If ScoreToBeat is provided, then the result will be the move
	// that maximizes the probability of achieving a final score
	// greater than the given score. The GameState must also contain
	// the current total score.
	ScoreToBeat int
}

// Optimal move response returns the best move to make.
type OptimalMoveResponse struct {
	// HeldDice are returned if the TurnState of the request is
	// Hold1 or Hold2.
	HeldDice []int
	// BoxFilled is returned if the TurnState of the request is FillBox.
	BoxFilled int
	// Value is the value attributed to this move.
	// For expected value, it is the expected remaining value.
	// For ScoreToBeat, it is the probability of beating the score.
	Value float32
	// True if the best move to achieve the desired score to beat is to quit.
	StartOver bool
}

// OutcomeDistributionRequest gets the range of possible outcomes
// for all possible choices at the current turn state.
type OutcomeDistributionRequest struct {
	GameState GameState
	TurnState TurnState
}

// HoldChoices are populated if TurnState.Step is Hold1 or Hold2.
// FillChoices are populated if TurnState.Step is FillBox (after third roll).
type OutcomeDistributionResponse struct {
	HoldChoices []HoldChoice
	FillChoices []FillChoice
}

// HoldChoice represents one possible choice of dice to hold,
// and the associated final outcome if that choice is made.
type HoldChoice struct {
	HeldDice                   []int
	ExpectedRemainingScore     float32
	RemainingScoreDistribution []float32
}

// FillChoice represents the outcome of filling a particular box with
// a given roll.
type FillChoice struct {
	BoxFilled                  int
	ExpectedRemainingScore     float32
	RemainingScoreDistribution []float32
}
